name: Publish to Maven Central
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  publish:
    # Only run if the PR was merged
    if: github.event.pull_request.merged == true
    name: Release build and publish
    runs-on: macos-latest
    permissions:
      contents: write # Required to create a release
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for generating release notes

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Extract Lucide version
        id: lucide_version
        run: |
          LUCIDE_VER=$(grep "^lucide =" gradle/libs.versions.toml | cut -d '"' -f 2)
          echo "version=$LUCIDE_VER" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.lucide_version.outputs.version }}
          target_commitish: main
          body: |
            This release includes icons from **Lucide v${{ steps.lucide_version.outputs.version }}**.
          generate_release_notes: true

      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
